import type { Metadata } from "next";
import Navbar from "@/components/ui/layout/navbar";

/* 
const cal_sans = Cal_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-cal-sans",
  display: "swap",
}); */

export const metadata: Metadata = {
  title: "Progressive Medical Corporation",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Navbar />
      <main>{children}</main>
    </div>
  );
}
